### ISSUE TITLE
d33b31f breaks add_clangcheck() interface

### ISSUE THREAD

**Issue by latk** [Eyescale/CMake#410]
Commit d33b31f7cb198f4dc87126060016e2899fc27daa changes the interface of `add_clangcheck()` – again. Previously, the syntax seems to have been

``` cmake
add_clangckeck(<target-name>
    [UNUSED_FUNCTIONS]
    [STYLE]
    [POSSIBLE_ERROR]
    [FAIL_ON_WARNINGS]
    [EXCLUDE_PATTERN <pattern>])
```

, but now it is

``` cmake
add_clangcheck(<target-name> <excluded-files-array>)
```

and documented as

``` cmake
add_clangcheck(<target-name>
    [UNUSED_FUNCTIONS]
    [STYLE]
    [POSSIBLE_ERROR]
    [FAIL_ON_WARNINGS])
```

This means that an invocation such as `add_clangeck(mytarget)` is no longer valid, and fails with the rather unhelpful error

``` none
CMake Error at <redacted>/CMakeLists.txt:24 (add_clangcheck):
  add_clangcheck Function invoked with incorrect arguments for function
  named: add_clangcheck
```

. Please either drop `clangcheckTargets` from the documented public interface in the README of this repository, or commit to a stable-ish, correctly documented, and backwards-compatible interface.

If backwards compatibility is not your thing, it might be worth marking known-good states as a release and encouraging users to clone that, rather than tracking `master` as suggested in the README:

> \[...]To use it, create a .gitexternals file in your project:
> 
> ``` none
> # -*- mode: cmake -*-
> # CMake/common https://github.com/Eyescale/CMake.git master
> ```
> Copy GitExternal from this repository to CMake/, and use it in your top-level CMakeLists.txt as follows:
> 
> ``` cmake
> list(APPEND CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/CMake
>                               ${CMAKE_SOURCE_DIR}/CMake/common)
> include(GitExternal)
> include(Common)
> ```
>
> This will clone the latest version of this repository into your project at the beginning of the CMake run, and make all its features available. Run the 'update' target after the first successful cmake run to pin the git external to a SHA1 tag instead of a moving master tag.

(Which `update` target? Maybe my *real* problem is that I can't figure out how to do that…)

**Comment by tribal-tec** [comment]
I'll try to bring back the API for this function. I was not aware it was documented to be public. Sorry for the inconvenience.

Regarding stable/known-good states: We are tracking a (stable) SHA-1 in .gitexternals rather than master in all our projects. I'll revise the documentation if this is not clear enough. The *update* target refers to call 'make update' after the CMake run to update the tag from master to the current SHA-1.
