### ISSUE TITLE
Project-doxycopy does nothing

### ISSUE THREAD

**Issue by hernando** [Eyescale/CMake#429]
Has anybody used this target successfully recently?
I'm trying to use it for Brion but the target is empty.

**Comment by rdumusc** [comment]
On 11/04/2015 03:49 PM, hernando wrote:
>
> Has anybody used this target successfully recently?
> I'm trying to use it for Brion but the target is empty.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Eyescale/CMake/issues/429>.
>
I got the same issue. Make sure the documentation repo is named
BlueBrain (and located as stated in the error message) and re-run cmake
to get a non-empty the doxycopy target.

**Comment by hernando** [comment]
Thanks, I was coming to the some conclusion by reading the code at DoxygenRule.cmake.
I think the target should print the reason for which it does nothing instead of letting you figure it out. I'm going to open a PR for this.

**Comment by rdumusc** [comment]
Well, maybe it can be improved, but it already tells you the expected location of the missing documentation folder...

**Comment by hernando** [comment]
It should print it. But when I run this target I got no output.

    [hernando@bbpviz1 build]$ make Brion-doxycopy
    Built target Brion-doxycopy
    [hernando@bbpviz1 build]$

**Comment by bilgili** [comment]
try this:

make install
make doxycopy

**Comment by rdumusc** [comment]
Strange, when I did it the comment did get printed...
