### ISSUE TITLE
Remove per-system defines.h file generation

### ISSUE THREAD

**Issue by tribal-tec** [Eyescale/CMake#492]
As mentioned/discussed in https://github.com/Eyescale/CMake/pull/491

**Comment by eile** [comment]
Initial use case was to be able to have two different installations on the same filesystem, e.g., linux and windows.

**Comment by rdumusc** [comment]
I find it improbable that someone would want to deploy on the same filesystem AND in the the same folder headers/binaries for completely different OSes. There may be conflicts with text file encoding, or the libs may be overwriting each other (if they all have .a extension for example) so I vote for this simplification.
