### ISSUE TITLE
Complex bug with recursive git_subprojects and system packge installed

### ISSUE THREAD

**Issue by rdumusc** [Eyescale/CMake#557]
Setup:
* desktopstreamer system package installed (/usr/share/Deflect/CMake/DeflectTargets.cmake correctly indicated a dependency of DeflectQt on Qt5::Quick)
* meta-project with:
    git_subproject(Deflect https://github.com/BlueBrain/Deflect.git 0d10736)
    git_subproject(Tide https://github.com/BlueBrain/Tide.git 907ba3b)

Fails to configure with:
```
CMake Error at CMake/common/CommonLibrary.cmake:112 (add_library):
  Target "TideMaster" links to target "Qt5::Quick" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  Tide/tide/master/CMakeLists.txt:192 (common_library)
[... multiple occurencies ....]
```

Just removing the first git_subproject(Deflect), or configuring Tide independently, or uninstalling the Deflect system package all work around the problem.

**Comment by tribal-tec** [comment]
Deflect does not properly declare Qt5Quick as a dependency; it misses 
```
set(DEFLECT_DEPENDENT_LIBRARIES Qt5Quick)
```
somewhere before include(CommonPackageConfig) to resolved the Qt5::Quick target.

**Comment by rdumusc** [comment]
This indeed fixes the problem, thanks a lot. Strange that you need such a complex setup to observe the problem. One important detail is to use the package name (Qt5Quick) instead of the target name (Qt5::Quick) like in set(DEFLECTQT_LINK_LIBRARIES PUBLIC).

**Comment by tribal-tec** [comment]
Maybe there's a spot to document this better. If a target is 'leaking', the corresponding find_dependency(...) call in the ProjectConfig.cmake has to be added via PROJECT_DEPENDENT_LIBRARIES so that CMake finds the target. Not needed in a super/subproject setup.

**Comment by rdumusc** [comment]
Something like this, yes, maybe in the readme.md so that people don't miss it.
We could also find a more precise name for the variable. It is not really LIBRARIES or target but its corresponding package name for find_package.
