### ISSUE TITLE
"make prj-doxygen" invokes a "make install"

### ISSUE THREAD

**Issue by jmespadero** [Eyescale/CMake#562]
Hi,

I have tried to generate doxygen documentation of a project using the command `make prj-doxygen` and got this error:
```
Scanning dependencies of target doxygen_install_prj
-- Install configuration: "Debug"
CMake Error at cmake_install.cmake:36 (file):
  file cannot create directory: /usr/share/prj/CMake.  Maybe need
  administrative privileges.
```

This error appears because cmake is trying to execute a "make install" before of building the documentation. Since I don't have declared the CMAKE_INSTALL_PREFIX variable, it tries to do an install into my /usr/ directory. Opppps!

As a workaround, I have defined CMAKE_INSTALL_PREFIX to a temporal directory, which is enough to go ahead and build the doxygen documentation under {PROJECT_BINARY_DIR}/doc. 

I have peek into file [DoxygenRule.cmake](https://github.com/Eyescale/CMake/blob/master/DoxygenRule.cmake#L125) and found that there is a DEPENDS at line 125:
```cmake
add_custom_target(${PROJECT_NAME}-doxygen
  ${DOXYGEN_EXECUTABLE} ${DOXYGEN_CONFIG_FILE}
  WORKING_DIRECTORY ${PROJECT_BINARY_DIR}/doc
  COMMENT "Generating ${PROJECT_NAME} API documentation using doxygen" VERBATIM
DEPENDS ${PROJECT_NAME}-install project_info_${PROJECT_NAME})
```

Why do you need to install the project before of building the documentation?
It is safe to remove that dependency?

**Comment by eile** [comment]
We run doxygen on the installed headers, to not generate documentation for internal stuff. One could in theory install all PUBLIC_HEADERS and installed examples in CMAKE_BINARY_DIR and run doxygen against this, but 1) someone has to do the CMake magic and 2) it would be a bit brittle.

**Comment by jmespadero** [comment]
That makes sense for projects with both public and private parts.
I would like to do it myself, but I think it is beyond my cmake knowledge. 
Thanks  for the answer, anyway.
